### ISSUE TITLE
twitcasting推送无法正常工作

### ISSUE THREAD

**Issue by ns920** [Sora233/DDBOT#176]
不知道是不是我配置写错了
> time="2022-10-02T17:17:15+08:00" level=error msg="StateManager twitcasting: Fresh panic recoved" Name=twitcasting module=concern stack="goroutine 145 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x83\ngithub.com/Sora233/DDBOT/lsp/concern.(*StateManager).Fresh.func1(0x126e4770, 0x126e47a4, 0x1265da80)\n\t/github/workspace/lsp/concern/stateManager.go:552 +0x4e\npanic({0x1344f20, 0x1b6d758})\n\t/usr/local/go/src/runtime/panic.go:1038 +0x1bc\ngithub.com/Sora233/DDBOT/lsp/twitcasting.(*TwitCastConcern).tcFresh.func1({0x1273fccc, 0x4}, {0x1311000, 0x12a23428})\n\t/github/workspace/lsp/twitcasting/concern.go:133 +0x187\ngithub.com/Sora233/DDBOT/lsp/concern.(*StateManager).EmitQueueFresher.func1({0x15855a4, 0x12714060}, 0x1265da80)\n\t/github/workspace/lsp/concern/stateManager.go:531 +0x26c\ngithub.com/Sora233/DDBOT/lsp/concern.(*StateManager).Fresh(0x126e4770, 0x126e47a4, 0x1265da80)\n\t/github/workspace/lsp/concern/stateManager.go:559 +0x9a\ncreated by github.com/Sora233/DDBOT/lsp/concern.(*StateManager).Start\n\t/github/workspace/lsp/concern/stateManager.go:505 +0x328\n"

**Comment by ns920** [comment]
似乎报错不影响正常工作
