### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by Sora233** [Sora233/DDBOT#61]
时有发生但没找到问题，一个是代码里面没有发送ServiceElement的代码，另外一个是lsp.sendGroupMessage有检查元素非nil。
```
goroutine 72 [running]:
runtime/debug.Stack(0xc001e9a780, 0xd40080, 0x1589920)
 /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/Sora233/DDBOT/lsp.(*Lsp).ConcernNotify.func1(0xc0000709c0, 0xc0005bfbb0)
 /home/ubuntu/go/src/github.com/Sora233/DDBOT/lsp/notify.go:21 +0x76
panic(0xd40080, 0x1589920)
 /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/Mrs4s/MiraiGo/message.(*ServiceElement).Pack(0x0, 0xfcd440, 0x0, 0x7f7d6847adb8)
 /home/ubuntu/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20210518070025-f145000ac0ef/message/pack.go:133 +0x37
github.com/Mrs4s/MiraiGo/message.ToProtoElems(0xc001b54a40, 0x1, 0x1, 0xc001e9ab01, 0x489d5f, 0xd2d4c0, 0xc00260d140)
 /home/ubuntu/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20210518070025-f145000ac0ef/message/message.go:313 +0x59a
github.com/Mrs4s/MiraiGo/client.(*QQClient).buildGroupSendingPacket(0xc0001e4800, 0x6ca76e6, 0x160e2b19c, 0x0, 0x0, 0xc001b54a40, 0x1, 0x1, 0xc003555ff0, 0xc001e9ad98, ...)
 /home/ubuntu/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20210518070025-f145000ac0ef/client/group_msg.go:256 +0x17b
github.com/Mrs4s/MiraiGo/client.(*QQClient).sendGroupMessage(0xc0001e4800, 0x6ca76e6, 0xc001e9ae00, 0xc001e9ae00, 0x0)
 /home/ubuntu/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20210518070025-f145000ac0ef/client/group_msg.go:130 +0x7f4
github.com/Mrs4s/MiraiGo/client.(*QQClient).SendGroupMessage(0xc0001e4800, 0x6ca76e6, 0xc001e9b4f8, 0x0, 0x0, 0x0, 0x8)
 /home/ubuntu/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20210518070025-f145000ac0ef/client/group_msg.go:50 +0x308
github.com/Sora233/DDBOT/lsp.(*Lsp).sendGroupMessage(0xc0000709c0, 0x6ca76e6, 0xc001c074f8, 0xc001c074f8)
 /home/ubuntu/go/src/github.com/Sora233/DDBOT/lsp/module.go:496 +0x118
github.com/Sora233/DDBOT/lsp.(*Lsp).ConcernNotify(0xc0000709c0, 0xc0005bfbb0)
 /home/ubuntu/go/src/github.com/Sora233/DDBOT/lsp/notify.go:61 +0x1173
created by github.com/Sora233/DDBOT/lsp.(*Lsp).Start
 /home/ubuntu/go/src/github.com/Sora233/DDBOT/lsp/module.go:400 +0x53
```

**Comment by Sora233** [comment]
大概是miraigo的race condition？但由于arm不能开启race detector，先搁置。
